[package]
name = "rust-texas-holdem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
phf = { version = "0.11.2", features = ["macros"] }
rand = "0.8"
term_size = "0.3"

